from rest_framework.serializers import ModelSerializer

from cinguloapi.activities.models import UserActivity, JanuaryDailyActivity, FebruaryDailyActivity, MarchDailyActivity, \
    AprilDailyActivity, MayDailyActivity, JuneDailyActivity, JulyDailyActivity, AugustDailyActivity, SeptemberDailyActivity, \
    OctoberDailyActivity, NovemberDailyActivity, DecemberDailyActivity, DailyActivity


class UserActivitySerializer(ModelSerializer):
    class Meta:
        model = UserActivity
        fields = ('user_id', 'activities')


class JanuaryDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = JanuaryDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class FebruaryDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = FebruaryDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  )


class MarchDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = MarchDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class AprilDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = AprilDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  )


class MayDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = MayDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class JuneDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = JuneDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  )


class JulyDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = JulyDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class AugustDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = AugustDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class SeptemberDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = SeptemberDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  )


class OctoberDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = OctoberDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class NovemberDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = NovemberDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  )


class DecemberDailyActivitySerializer(ModelSerializer):
    class Meta:
        model = DecemberDailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  )


class DailyActivitySerializer(ModelSerializer):
    class Meta:
        model = DailyActivity
        fields = ('day_01',
                  'day_02',
                  'day_03',
                  'day_04',
                  'day_05',
                  'day_06',
                  'day_07',
                  'day_08',
                  'day_09',
                  'day_10',
                  'day_11',
                  'day_12',
                  'day_13',
                  'day_14',
                  'day_15',
                  'day_16',
                  'day_17',
                  'day_18',
                  'day_19',
                  'day_20',
                  'day_21',
                  'day_22',
                  'day_23',
                  'day_24',
                  'day_25',
                  'day_26',
                  'day_27',
                  'day_28',
                  'day_29',
                  'day_30',
                  'day_31',
                  'day_32',
                  'day_33',
                  'day_34',
                  'day_35',
                  'day_36',
                  'day_37',
                  'day_38',
                  'day_39',
                  'day_40',
                  'day_41',
                  'day_42',
                  'day_43',
                  'day_44',
                  'day_45',
                  'day_46',
                  'day_47',
                  'day_48',
                  'day_49',
                  'day_50',
                  'day_51',
                  'day_52',
                  'day_53',
                  'day_54',
                  'day_55',
                  'day_56',
                  'day_57',
                  'day_58',
                  'day_59',
                  'day_60',
                  'day_61',
                  'day_62',
                  'day_63',
                  'day_64',
                  'day_65',
                  'day_66',
                  'day_67',
                  'day_68',
                  'day_69',
                  'day_70',
                  'day_71',
                  'day_72',
                  'day_73',
                  'day_74',
                  'day_75',
                  'day_76',
                  'day_77',
                  'day_78',
                  'day_79',
                  'day_80',
                  'day_81',
                  'day_82',
                  'day_83',
                  'day_84',
                  'day_85',
                  'day_86',
                  'day_87',
                  'day_88',
                  'day_89',
                  'day_90',
                  'day_91',
                  'day_92',
                  'day_93',
                  'day_94',
                  'day_95',
                  'day_96',
                  'day_97',
                  'day_98',
                  'day_99',
                  'day_100',
                  'day_101',
                  'day_102',
                  'day_103',
                  'day_104',
                  'day_105',
                  'day_106',
                  'day_107',
                  'day_108',
                  'day_109',
                  'day_110',
                  'day_111',
                  'day_112',
                  'day_113',
                  'day_114',
                  'day_115',
                  'day_116',
                  'day_117',
                  'day_118',
                  'day_119',
                  'day_120',
                  'day_121',
                  'day_122',
                  'day_123',
                  'day_124',
                  'day_125',
                  'day_126',
                  'day_127',
                  'day_128',
                  'day_129',
                  'day_130',
                  'day_131',
                  'day_132',
                  'day_133',
                  'day_134',
                  'day_135',
                  'day_136',
                  'day_137',
                  'day_138',
                  'day_139',
                  'day_140',
                  'day_141',
                  'day_142',
                  'day_143',
                  'day_144',
                  'day_145',
                  'day_146',
                  'day_147',
                  'day_148',
                  'day_149',
                  'day_150',
                  'day_151',
                  'day_152',
                  'day_153',
                  'day_154',
                  'day_155',
                  'day_156',
                  'day_157',
                  'day_158',
                  'day_159',
                  'day_160',
                  'day_161',
                  'day_162',
                  'day_163',
                  'day_164',
                  'day_165',
                  'day_166',
                  'day_167',
                  'day_168',
                  'day_169',
                  'day_170',
                  'day_171',
                  'day_172',
                  'day_173',
                  'day_174',
                  'day_175',
                  'day_176',
                  'day_177',
                  'day_178',
                  'day_179',
                  'day_180',
                  'day_181',
                  'day_182',
                  'day_183',
                  'day_184',
                  'day_185',
                  'day_186',
                  'day_187',
                  'day_188',
                  'day_189',
                  'day_190',
                  'day_191',
                  'day_192',
                  'day_193',
                  'day_194',
                  'day_195',
                  'day_196',
                  'day_197',
                  'day_198',
                  'day_199',
                  'day_200',
                  'day_201',
                  'day_202',
                  'day_203',
                  'day_204',
                  'day_205',
                  'day_206',
                  'day_207',
                  'day_208',
                  'day_209',
                  'day_210',
                  'day_211',
                  'day_212',
                  'day_213',
                  'day_214',
                  'day_215',
                  'day_216',
                  'day_217',
                  'day_218',
                  'day_219',
                  'day_220',
                  'day_221',
                  'day_222',
                  'day_223',
                  'day_224',
                  'day_225',
                  'day_226',
                  'day_227',
                  'day_228',
                  'day_229',
                  'day_230',
                  'day_231',
                  'day_232',
                  'day_233',
                  'day_234',
                  'day_235',
                  'day_236',
                  'day_237',
                  'day_238',
                  'day_239',
                  'day_240',
                  'day_241',
                  'day_242',
                  'day_243',
                  'day_244',
                  'day_245',
                  'day_246',
                  'day_247',
                  'day_248',
                  'day_249',
                  'day_250',
                  'day_251',
                  'day_252',
                  'day_253',
                  'day_254',
                  'day_255',
                  'day_256',
                  'day_257',
                  'day_258',
                  'day_259',
                  'day_260',
                  'day_261',
                  'day_262',
                  'day_263',
                  'day_264',
                  'day_265',
                  'day_266',
                  'day_267',
                  'day_268',
                  'day_269',
                  'day_270',
                  'day_271',
                  'day_272',
                  'day_273',
                  'day_274',
                  'day_275',
                  'day_276',
                  'day_277',
                  'day_278',
                  'day_279',
                  'day_280',
                  'day_281',
                  'day_282',
                  'day_283',
                  'day_284',
                  'day_285',
                  'day_286',
                  'day_287',
                  'day_288',
                  'day_289',
                  'day_290',
                  'day_291',
                  'day_292',
                  'day_293',
                  'day_294',
                  'day_295',
                  'day_296',
                  'day_297',
                  'day_298',
                  'day_299',
                  'day_300',
                  'day_301',
                  'day_302',
                  'day_303',
                  'day_304',
                  'day_305',
                  'day_306',
                  'day_307',
                  'day_308',
                  'day_309',
                  'day_310',
                  'day_311',
                  'day_312',
                  'day_313',
                  'day_314',
                  'day_315',
                  'day_316',
                  'day_317',
                  'day_318',
                  'day_319',
                  'day_320',
                  'day_321',
                  'day_322',
                  'day_323',
                  'day_324',
                  'day_325',
                  'day_326',
                  'day_327',
                  'day_328',
                  'day_329',
                  'day_330',
                  'day_331',
                  'day_332',
                  'day_333',
                  'day_334',
                  'day_335',
                  'day_336',
                  'day_337',
                  'day_338',
                  'day_339',
                  'day_340',
                  'day_341',
                  'day_342',
                  'day_343',
                  'day_344',
                  'day_345',
                  'day_346',
                  'day_347',
                  'day_348',
                  'day_349',
                  'day_350',
                  'day_351',
                  'day_352',
                  'day_353',
                  'day_354',
                  'day_355',
                  'day_356',
                  'day_357',
                  'day_358',
                  'day_359',
                  'day_360',
                  'day_361',
                  'day_362',
                  'day_363',
                  'day_364',
                  'day_365',
                  )
