# Generated by Django 3.2.4 on 2021-06-26 15:36

import cinguloapi.activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JanuaryDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_01', models.JSONField()),
                ('day_02', models.JSONField()),
                ('day_03', models.JSONField()),
                ('day_04', models.JSONField()),
                ('day_05', models.JSONField()),
                ('day_06', models.JSONField()),
                ('day_07', models.JSONField()),
                ('day_08', models.JSONField()),
                ('day_09', models.JSONField()),
                ('day_10', models.JSONField()),
                ('day_11', models.JSONField()),
                ('day_12', models.JSONField()),
                ('day_13', models.JSONField()),
                ('day_14', models.JSONField()),
                ('day_15', models.JSONField()),
                ('day_16', models.JSONField()),
                ('day_17', models.JSONField()),
                ('day_18', models.JSONField()),
                ('day_19', models.JSONField()),
                ('day_20', models.JSONField()),
                ('day_21', models.JSONField()),
                ('day_22', models.JSONField()),
                ('day_23', models.JSONField()),
                ('day_24', models.JSONField()),
                ('day_25', models.JSONField()),
                ('day_26', models.JSONField()),
                ('day_27', models.JSONField()),
                ('day_28', models.JSONField()),
                ('day_29', models.JSONField()),
                ('day_30', models.JSONField()),
                ('day_31', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.JSONField(verbose_name=cinguloapi.activities.models.JanuaryDailyActivity)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activities', models.JSONField()),
            ],
        ),
    ]
